// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/feed.ts";
import * as $3 from "./routes/api/refresh.ts";
import * as $4 from "./routes/api/send.ts";
import * as $5 from "./routes/api/verify.ts";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/App.tsx";
import * as $$1 from "./islands/Entry.tsx";
import * as $$2 from "./islands/Feed.tsx";
import * as $$3 from "./islands/Login.tsx";
import * as $$4 from "./islands/Navbar.tsx";
import * as $$5 from "./islands/Post.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/feed.ts": $2,
    "./routes/api/refresh.ts": $3,
    "./routes/api/send.ts": $4,
    "./routes/api/verify.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/App.tsx": $$0,
    "./islands/Entry.tsx": $$1,
    "./islands/Feed.tsx": $$2,
    "./islands/Login.tsx": $$3,
    "./islands/Navbar.tsx": $$4,
    "./islands/Post.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
