// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/add.ts";
import * as $5 from "./routes/api/changelog.ts";
import * as $6 from "./routes/api/discovery.ts";
import * as $7 from "./routes/api/feed.ts";
import * as $8 from "./routes/api/friends.ts";
import * as $9 from "./routes/api/me.ts";
import * as $10 from "./routes/api/refresh.ts";
import * as $11 from "./routes/api/send.ts";
import * as $12 from "./routes/api/stats.ts";
import * as $13 from "./routes/api/user.ts";
import * as $14 from "./routes/api/verify.ts";
import * as $15 from "./routes/discovery.tsx";
import * as $16 from "./routes/index.tsx";
import * as $17 from "./routes/me.tsx";
import * as $18 from "./routes/stats.tsx";
import * as $19 from "./routes/user/[id].tsx";
import * as $$0 from "./islands/App.tsx";
import * as $$1 from "./islands/Changelog.tsx";
import * as $$2 from "./islands/Comments.tsx";
import * as $$3 from "./islands/Data.tsx";
import * as $$4 from "./islands/Discovery.tsx";
import * as $$5 from "./islands/Entry.tsx";
import * as $$6 from "./islands/Error.tsx";
import * as $$7 from "./islands/Feed.tsx";
import * as $$8 from "./islands/Login.tsx";
import * as $$9 from "./islands/Me.tsx";
import * as $$10 from "./islands/Navbar.tsx";
import * as $$11 from "./islands/Post.tsx";
import * as $$12 from "./islands/User.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/add.ts": $4,
    "./routes/api/changelog.ts": $5,
    "./routes/api/discovery.ts": $6,
    "./routes/api/feed.ts": $7,
    "./routes/api/friends.ts": $8,
    "./routes/api/me.ts": $9,
    "./routes/api/refresh.ts": $10,
    "./routes/api/send.ts": $11,
    "./routes/api/stats.ts": $12,
    "./routes/api/user.ts": $13,
    "./routes/api/verify.ts": $14,
    "./routes/discovery.tsx": $15,
    "./routes/index.tsx": $16,
    "./routes/me.tsx": $17,
    "./routes/stats.tsx": $18,
    "./routes/user/[id].tsx": $19,
  },
  islands: {
    "./islands/App.tsx": $$0,
    "./islands/Changelog.tsx": $$1,
    "./islands/Comments.tsx": $$2,
    "./islands/Data.tsx": $$3,
    "./islands/Discovery.tsx": $$4,
    "./islands/Entry.tsx": $$5,
    "./islands/Error.tsx": $$6,
    "./islands/Feed.tsx": $$7,
    "./islands/Login.tsx": $$8,
    "./islands/Me.tsx": $$9,
    "./islands/Navbar.tsx": $$10,
    "./islands/Post.tsx": $$11,
    "./islands/User.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
